module.exports = {
  User: require('./User'),
  Branch: require('./Branch'),
  Patient: require('./Patient'),
  Doctor: require('./Doctor'),
  Staff: require('./Staff'),
  Service: require('./Service'),
  Appointment: require('./Appointment'),
  Visit: require('./Visit'),
  Prescription: require('./Prescription'),
  LabTest: require('./LabTest'),
  Radiology: require('./Radiology'),
  Procedure: require('./Procedure'),
  Referral: require('./Referral'),
  Invoice: require('./Invoice'),
  Notification: require('./Notification'),
  Queue: require('./Queue'),
  AuditLog: require('./AuditLog'),
  Attachment: require('./Attachment'),
};
